### ISSUE TITLE
Creating secondary zones always shows changed.

### ISSUE THREAD

**Issue by danielgriggs** [ns1/ns1-ansible-modules#24]
Creating secondary zones with the ns1_zone module always shows changed even when nothing has changed.

    - name: Push all domains to NS One
      ns1_zone:
        name: "{{ item.domain }}"
        secondary: "{{ nsone_settings_secondaries.default }}"
        apiKey: "{{ nsone_api_key }}"
      loop: "{{ zones.list  }}"
      loop_control:
        label: "{{ item.domain }} -> {{ item.e }}"

Happy to share more details privately.

**Comment by rupa** [comment]
Hi, thanks for reporting this issue. I haven't looked into it yet, but have a suspicion that `zones.list` is not ordered, and sorting it might help?

In any event, we've got more bandwidth and sprucing up the ansible stuff is a priority, so we can certainly look into improving this. Might be a good time to chat with support and discuss your issues/needs/desires for our ansible modules, so we can make sure we're on the same page with upcoming work.

**Comment by danielgriggs** [comment]
Hi,

Thanks for getting back to me, I just checked and the zone.list is sorted in alphabetical order. Unless there is a different style ordering I'm not sure that's it. I'll log a ticket with support.

**Comment by rupa** [comment]
ah well, I had hope, but didn't have my hopes up. thanks again, we'll get this looked into

**Comment by danielgriggs** [comment]
Support came back and said it's best to deal with it via the GitHub tracker.
The ticket via support was request id 22511

**Comment by danielgriggs** [comment]
Is there any further information required for this?

Daniel

**Comment by rupa** [comment]
Hi, sorry for delayed response (holidays). Yep, we've got a ticket going about this and it should be picked up for dev shortly.

**Comment by mburtless** [comment]
This is due to the fact that the module does not currently perform a diff only on the configurable keys within the `secondary` object, but instead just compares the object it GETs from NS1 to the one that has been defined in the Ansible play.

The response from the API contains a number of fields within `secondary` that are not defined in the Ansible play and therefore will never be equal.  Accordingly a change will always be reported.

I'll get a PR going to define typed suboptions for `secondary` and perform a more selective diff.

**Comment by mburtless** [comment]
This has been fixed in #26.  This can be considered a breaking change as it adds suboptions to the arg spec for `secondary` and no longer accepts a dict with arbitrary keys.  Accordingly, this will be release in a new major version of the `ns1` role on Galaxy.

Holding off on cutting that release for the moment, because there are a few other changes that should get in first, but the updated module can be used by cloning this repo directly.

**Comment by danielgriggs** [comment]
Okay, nice, is it worth me giving it a test run now?

Daniel.

**Comment by danielgriggs** [comment]
I was just reading over the changes and it looks like the secondary option no longer supports setting a TSIG key for zone transfers from the primary? or does the sanitise params not dig down further into the param? Sorry Python isn't my strong suite.

Daniel

**Comment by danielgriggs** [comment]
Oh yep, just did some testing, setting tsig doesn't work

"Unsupported parameters for (ns1_zone) module: tsig found in secondary. Supported parameters include: enabled, other_ips, other_ports, primary_ip, primary_port"

Daniel

**Comment by mburtless** [comment]
Thanks for testing this out.  Sorry about that, forgot to call out that I
pulled that out of the initial refactor.

It's the backlog to add real suboptions for TSIG before we cut the new
release, but I'll add a dict suboption back in for it today so it's at
least as supported as it was previously.

**Comment by mburtless** [comment]
I've added in a suboption for TSIG and all of it's relevant configuration options in #28.

**Comment by mburtless** [comment]
Closing this issue as suboptions for `secondary` were released in `v3.0.0` of this role, which is available now via Galaxy.  Feel free to open a new issue if you're still running into any issues.
